-- vim.api.nvim_create_autocmd("VimEnter", {
--   command = "set nornu nonu | Neotree toggle",
-- })

-- This will run last in the setup process and is a good place to configure
-- things like custom filetypes. This just pure lua so anything that doesn't
-- fit in the normal config locations above can go here

-- Set up custom filetypes
-- vim.filetype.add {
--   extension = {
--     foo = "fooscript",
--   },
--   filename = {
--     ["Foofile"] = "fooscript",
--   },
--   pattern = {
--     ["~/%.config/foo/.*"] = "fooscript",
--   },
-- }
--
-- vim.api.nvim_create_autocmd("FileType", {
--   -- You can set pattern = "*" but it will also display spell errors in buffers like lazygit
--   pattern = { "lua", "javascript", "typescript", "javascriptreact", "typescriptreact" },
--   callback = function()
--     vim.opt_local.spell = true
--     vim.opt_local.spelllang = "en_us"
--     vim.opt_local.spelloptions = "camel"
--     vim.opt_local.spellcapcheck = ""
--   end,
-- })
